labelPRBasedOnFilePath:
  ci:
    - .github/*
    - .github/**/*

  dependencies:
    - uv.lock
    - pyproject.toml

  'awesome: projects':
    - awesome/projects/*
    - awesome/projects/**/*

  scripts:
    - scripts/*
    - scripts/**/*

firstPRWelcomeComment: >
  Thanks for opening this pull request! Please check out our contributing guidelines.

verifyTitles:
  titleRegexp: ^(feat|feat!|fix|fix!|docs|refactor|refactor!|test|chore)\((release|docs|deps|deps-dev|scripts|awesome:projects|ci)\):.*
  alwaysUsePrTitle: true
  validateEitherPrOrSingleCommitTitle: true
  statusTitle: 'Title Validator'
  successMessage: 'Validation successful!'
  failureMessage: 'Wrong ${type} title: ${title}'
