labelPRBasedOnFilePath:
  ci:
    - .github/*
    - .github/**/*

  dependencies:
    - uv.lock
    - pyproject.toml

  awesome:
    - awesome/*
    - awesome/**/*
    - schemas/*

  "awesome: projects":
    - awesome/projects/*
    - awesome/projects/**/*

  scripts:
    - scripts/*
    - scripts/**/*

firstPRWelcomeComment: >
  Thanks for opening this pull request! Please check out our contributing guidelines.

verifyTitles:
  titleRegexp: ^(feat|feat!|fix|fix!|docs|refactor|refactor!|test|chore|build|ci)\((release|docs|deps|deps-dev|awesome:projects)\):.*
  alwaysUsePrTitle: true
  validateEitherPrOrSingleCommitTitle: true
  statusTitle: "Title Validator"
  successMessage: "Validation successful!"
  failureMessage: "Wrong ${type} title: ${title}"
